### ISSUE TITLE
nexus 6P, fresh flash with TWRP, NFC cannot be enabled

### ISSUE THREAD

**Issue by Zerqz** [AOSPA/android_device_huawei_angler#1]
angler / nexus 6P
PA version. 7.2.0-RELEASE

Freshly flashed, going through the settings, and NFC cannot be enabled. I don't know what the log for this would be, but if someone could point me in the direction I would be happy to post it.

**Comment by xboxfanj** [comment]
Fixed this since then, I don't receive notifications from this I guess.  Sorry I missed it.
